[pytest]
pythonpath = .
addopts =
    -p no:cacheprovider
    --html=reports/test-report.html
    --self-contained-html
norecursedirs =
    .git
    .pytest_cache
    pytest-tmp
    pytest-cache-files-*
    data
    reports
    third_party
    Cardentify-main
    __pycache__
